# Setup
title:        Kate Kight
tagline:      Sassy as fuck
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Kate Kight
  url:        

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
