# Setup
title:       <a href="http://www.katekight.com> Kate Kight </a>
tagline:      Sassy as fuck
baseurl:      "katekigh.com"
paginate:     1

# About/contact
author:
  name:       Kate Kight
  url:        http://katekight.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
