# Setup
title:        Kate Kight
tagline:      Sassy as fuck
baseurl:      "www.katekight.com"
paginate:     1

# About/contact
author:
  name:       Kate Kight
  url:        http://www.katekight.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
